package lk.ijse.dep10.shared;

public enum Header {

    /*message related*/
    MESSAGE,USERS,EXIT, NEW_USER,USER_NAME_EXISTS,SIGN_UP_SUCCESS,NEW_LOGIN,INVALID_LOGIN, VALID_LOGIN,USER_DETAILS,NEW_MESSENGER,USER_DETAILS_UPDATE
}
